//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Sheet.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Guides {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Guides() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD_Sheet.Resources.Views.Home.Guides", typeof(Guides).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult black dragon.
        /// </summary>
        public static string AdultBlackDragon {
            get {
                return ResourceManager.GetString("AdultBlackDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult blue dragon.
        /// </summary>
        public static string AdultBlueDragon {
            get {
                return ResourceManager.GetString("AdultBlueDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult brass dragon.
        /// </summary>
        public static string AdultBrassDragon {
            get {
                return ResourceManager.GetString("AdultBrassDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult silver dragon.
        /// </summary>
        public static string AdultSilverDragon {
            get {
                return ResourceManager.GetString("AdultSilverDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awakened shrub.
        /// </summary>
        public static string AwakenedShrub {
            get {
                return ResourceManager.GetString("AwakenedShrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awakened tree.
        /// </summary>
        public static string AwakenedTree {
            get {
                return ResourceManager.GetString("AwakenedTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        public static string Elf {
            get {
                return ResourceManager.GetString("Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        public static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play?.
        /// </summary>
        public static string HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        public static string GetString(string key)
        {
             return ResourceManager.GetString(key, resourceCulture);
        }
    }
}
