//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Sheet.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD_Sheet.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Page.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is dedicated to providing the best content and resources for your Dungeons &amp; Dragons adventures..
        /// </summary>
        public static string AboutPageDescription {
            get {
                return ResourceManager.GetString("AboutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Character.
        /// </summary>
        public static string CreateYourCharacter {
            get {
                return ResourceManager.GetString("CreateYourCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Guides.
        /// </summary>
        public static string ExploreGuides {
            get {
                return ResourceManager.GetString("ExploreGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dive into a treasure trove of knowledge and embark on your next adventure:.
        /// </summary>
        public static string ExploreGuidesDescription {
            get {
                return ResourceManager.GetString("ExploreGuidesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to begin your journey?.
        /// </summary>
        public static string ExploreGuidesDescription2 {
            get {
                return ResourceManager.GetString("ExploreGuidesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section and start exploring the vast world of Dungeons &amp; Dragons!.
        /// </summary>
        public static string ExploreGuidesDescription3end {
            get {
                return ResourceManager.GetString("ExploreGuidesDescription3end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string ExploreGuidesDescription3start {
            get {
                return ResourceManager.GetString("ExploreGuidesDescription3start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover expertly crafted guides and tutorials.
        /// </summary>
        public static string ExploreGuidesPoint1 {
            get {
                return ResourceManager.GetString("ExploreGuidesPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master the intricacies of character creation, world-building, and more.
        /// </summary>
        public static string ExploreGuidesPoint2 {
            get {
                return ResourceManager.GetString("ExploreGuidesPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your gameplay with valuable tips and strategies.
        /// </summary>
        public static string ExploreGuidesPoint3 {
            get {
                return ResourceManager.GetString("ExploreGuidesPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the powerful features of this page:.
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started?.
        /// </summary>
        public static string FeaturesDescription2 {
            get {
                return ResourceManager.GetString("FeaturesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Sheet Creator.
        /// </summary>
        public static string FeaturesPoint1 {
            get {
                return ResourceManager.GetString("FeaturesPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides and Tutorials.
        /// </summary>
        public static string FeaturesPoint2 {
            get {
                return ResourceManager.GetString("FeaturesPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides.
        /// </summary>
        public static string Guides {
            get {
                return ResourceManager.GetString("Guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
