//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Sheet.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyPolicy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD_Sheet.Resources.Views.Home.PrivacyPolicy", typeof(PrivacyPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to means a unique account created for You to access our Service or parts of our Service..
        /// </summary>
        public static string AccountDescription {
            get {
                return ResourceManager.GetString("AccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administered by: Us.
        /// </summary>
        public static string AdministredByUs {
            get {
                return ResourceManager.GetString("AdministredByUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        public static string Affiliate {
            get {
                return ResourceManager.GetString("Affiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority..
        /// </summary>
        public static string AffiliateDescription {
            get {
                return ResourceManager.GetString("AffiliateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Transactions.
        /// </summary>
        public static string BusinessTransactions {
            get {
                return ResourceManager.GetString("BusinessTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy..
        /// </summary>
        public static string BusinessTransactionsDescription {
            get {
                return ResourceManager.GetString("BusinessTransactionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By email: safranek2@spsejecna.cz.
        /// </summary>
        public static string ByEmail {
            get {
                return ResourceManager.GetString("ByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this Privacy Policy.
        /// </summary>
        public static string ChangesToThisPrivacyPolicy {
            get {
                return ResourceManager.GetString("ChangesToThisPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page..
        /// </summary>
        public static string ChangesToThisPrivacyPolicyDescription {
            get {
                return ResourceManager.GetString("ChangesToThisPrivacyPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy..
        /// </summary>
        public static string ChangesToThisPrivacyPolicyDescription2 {
            get {
                return ResourceManager.GetString("ChangesToThisPrivacyPolicyDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page..
        /// </summary>
        public static string ChangesToThisPrivacyPolicyDescription3 {
            get {
                return ResourceManager.GetString("ChangesToThisPrivacyPolicyDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Privacy.
        /// </summary>
        public static string ChildrensPrivacy {
            get {
                return ResourceManager.GetString("ChildrensPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers..
        /// </summary>
        public static string ChildrensPrivacyDescription {
            get {
                return ResourceManager.GetString("ChildrensPrivacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information..
        /// </summary>
        public static string ChildrensPrivacyDescription2 {
            get {
                return ResourceManager.GetString("ChildrensPrivacyDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting and Using Your Personal Data.
        /// </summary>
        public static string CollectingAndUsingYourPersonalData {
            get {
                return ResourceManager.GetString("CollectingAndUsingYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to DnD Sheet..
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company may use Personal Data for the following purposes:.
        /// </summary>
        public static string CompanyUsePersonalData {
            get {
                return ResourceManager.GetString("CompanyUsePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide and maintain our Service.
        /// </summary>
        public static string CompanyUsePersonalDataDescription {
            get {
                return ResourceManager.GetString("CompanyUsePersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , including to monitor the usage of our Service..
        /// </summary>
        public static string CompanyUsePersonalDataDescription2 {
            get {
                return ResourceManager.GetString("CompanyUsePersonalDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions about this Privacy Policy, You can contact us:.
        /// </summary>
        public static string ContactUsDescription {
            get {
                return ResourceManager.GetString("ContactUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses..
        /// </summary>
        public static string CookiesDescription {
            get {
                return ResourceManager.GetString("CookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on.
        /// </summary>
        public static string CookiesDescription2 {
            get {
                return ResourceManager.GetString("CookiesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article..
        /// </summary>
        public static string CookiesDescription3 {
            get {
                return ResourceManager.GetString("CookiesDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies or Browser Cookies..
        /// </summary>
        public static string CookiesOrBrowserCookies {
            get {
                return ResourceManager.GetString("CookiesOrBrowserCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies..
        /// </summary>
        public static string CookiesOrBrowserCookiesDescription {
            get {
                return ResourceManager.GetString("CookiesOrBrowserCookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies Policy / Notice Acceptance Cookies.
        /// </summary>
        public static string CookiesPolicyNoticeAcceptanceCookies {
            get {
                return ResourceManager.GetString("CookiesPolicyNoticeAcceptanceCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refers to:  Czech republic.
        /// </summary>
        public static string CountryDescription {
            get {
                return ResourceManager.GetString("CountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Your Personal Data.
        /// </summary>
        public static string DeleteYourPersonalData {
            get {
                return ResourceManager.GetString("DeleteYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You..
        /// </summary>
        public static string DeleteYourPersonalDataDescription {
            get {
                return ResourceManager.GetString("DeleteYourPersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service may give You the ability to delete certain information about You from within the Service..
        /// </summary>
        public static string DeleteYourPersonalDataDescription2 {
            get {
                return ResourceManager.GetString("DeleteYourPersonalDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us..
        /// </summary>
        public static string DeleteYourPersonalDataDescription3 {
            get {
                return ResourceManager.GetString("DeleteYourPersonalDataDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so..
        /// </summary>
        public static string DeleteYourPersonalDataDescription4 {
            get {
                return ResourceManager.GetString("DeleteYourPersonalDataDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to means any device that can access the Service such as a computer, a cellphone or a digital tablet..
        /// </summary>
        public static string DeviceDescription {
            get {
                return ResourceManager.GetString("DeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclosure of Your Personal Data.
        /// </summary>
        public static string DisclosureOfYourPersonalData {
            get {
                return ResourceManager.GetString("DisclosureOfYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For business transfers:.
        /// </summary>
        public static string ForBusinessTransfers {
            get {
                return ResourceManager.GetString("ForBusinessTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred..
        /// </summary>
        public static string ForBusinessTransfersDescription {
            get {
                return ResourceManager.GetString("ForBusinessTransfersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company..
        /// </summary>
        public static string ForBusinessTransfersDescription2 {
            get {
                return ResourceManager.GetString("ForBusinessTransfersDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For other purposes:.
        /// </summary>
        public static string ForOtherPurposes {
            get {
                return ResourceManager.GetString("ForOtherPurposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience..
        /// </summary>
        public static string ForOtherPurposesDescription {
            get {
                return ResourceManager.GetString("ForOtherPurposesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality Cookies.
        /// </summary>
        public static string FunctionalityCookies {
            get {
                return ResourceManager.GetString("FunctionalityCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation.
        /// </summary>
        public static string Interpretation {
            get {
                return ResourceManager.GetString("Interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation and Definitions.
        /// </summary>
        public static string InterpretationAndDefinitions {
            get {
                return ResourceManager.GetString("InterpretationAndDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural..
        /// </summary>
        public static string InterpretationDescription {
            get {
                return ResourceManager.GetString("InterpretationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: March 06, 2024.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law enforcement.
        /// </summary>
        public static string LawEnforcement {
            get {
                return ResourceManager.GetString("LawEnforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)..
        /// </summary>
        public static string LawEnforcementDescription {
            get {
                return ResourceManager.GetString("LawEnforcementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links to Other Websites.
        /// </summary>
        public static string LinksToOtherWebsites {
            get {
                return ResourceManager.GetString("LinksToOtherWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit..
        /// </summary>
        public static string LinksToOtherWebsitesDescription {
            get {
                return ResourceManager.GetString("LinksToOtherWebsitesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services..
        /// </summary>
        public static string LinksToOtherWebsitesDescription2 {
            get {
                return ResourceManager.GetString("LinksToOtherWebsitesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy..
        /// </summary>
        public static string MoreInformationAboutCookies {
            get {
                return ResourceManager.GetString("MoreInformationAboutCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary / Essential Cookies.
        /// </summary>
        public static string NecessaryEssentialCookies {
            get {
                return ResourceManager.GetString("NecessaryEssentialCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services..
        /// </summary>
        public static string NecessaryEssentialCookiesPurpose {
            get {
                return ResourceManager.GetString("NecessaryEssentialCookiesPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other legal requirements.
        /// </summary>
        public static string OtherLegalRequirements {
            get {
                return ResourceManager.GetString("OtherLegalRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:.
        /// </summary>
        public static string OtherLegalRequirementsDescription {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comply with a legal obligation.
        /// </summary>
        public static string OtherLegalRequirementsDescription2 {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect and defend the rights or property of the Company.
        /// </summary>
        public static string OtherLegalRequirementsDescription3 {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent or investigate possible wrongdoing in connection with the Service.
        /// </summary>
        public static string OtherLegalRequirementsDescription4 {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect the personal safety of Users of the Service or the public.
        /// </summary>
        public static string OtherLegalRequirementsDescription5 {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect against legal liability.
        /// </summary>
        public static string OtherLegalRequirementsDescription6 {
            get {
                return ResourceManager.GetString("OtherLegalRequirementsDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the performance of a contract:.
        /// </summary>
        public static string PerformanceOfAContract {
            get {
                return ResourceManager.GetString("PerformanceOfAContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service..
        /// </summary>
        public static string PerformanceOfAContractDescription {
            get {
                return ResourceManager.GetString("PerformanceOfAContractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is any information that relates to an identified or identifiable individual..
        /// </summary>
        public static string PersonalDataDescription {
            get {
                return ResourceManager.GetString("PersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:.
        /// </summary>
        public static string PersonalDataDescription2 {
            get {
                return ResourceManager.GetString("PersonalDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You..
        /// </summary>
        public static string PrivacyPolicyDescription {
            get {
                return ResourceManager.GetString("PrivacyPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy Generator.
        /// </summary>
        public static string PrivacyPolicyGenerator {
            get {
                return ResourceManager.GetString("PrivacyPolicyGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the purposes of this Privacy Policy:.
        /// </summary>
        public static string PrivacyPolicyPurposes {
            get {
                return ResourceManager.GetString("PrivacyPolicyPurposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention of Your Personal Data.
        /// </summary>
        public static string RetentionOfYourPersonalData {
            get {
                return ResourceManager.GetString("RetentionOfYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies..
        /// </summary>
        public static string RetentionOfYourPersonalDataDescription {
            get {
                return ResourceManager.GetString("RetentionOfYourPersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods..
        /// </summary>
        public static string RetentionOfYourPersonalDataDescription2 {
            get {
                return ResourceManager.GetString("RetentionOfYourPersonalDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security of Your Personal Data.
        /// </summary>
        public static string SecurityOfYourPersonalData {
            get {
                return ResourceManager.GetString("SecurityOfYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security..
        /// </summary>
        public static string SecurityOfYourPersonalDataDescription {
            get {
                return ResourceManager.GetString("SecurityOfYourPersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refers to the Website..
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used..
        /// </summary>
        public static string ServiceProviderDescription {
            get {
                return ResourceManager.GetString("ServiceProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use both Session and Persistent Cookies for the purposes set out below:.
        /// </summary>
        public static string SessionAndPersistentCookiesPurposes {
            get {
                return ResourceManager.GetString("SessionAndPersistentCookiesPurposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermsFeed website.
        /// </summary>
        public static string TermsFeedWebsite {
            get {
                return ResourceManager.GetString("TermsFeedWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contact You:.
        /// </summary>
        public static string ToContactYou {
            get {
                return ResourceManager.GetString("ToContactYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation..
        /// </summary>
        public static string ToContactYouDescription {
            get {
                return ResourceManager.GetString("ToContactYouDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage Your Account:.
        /// </summary>
        public static string ToManageYourAccount {
            get {
                return ResourceManager.GetString("ToManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user..
        /// </summary>
        public static string ToManageYourAccountDescription {
            get {
                return ResourceManager.GetString("ToManageYourAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage Your requests:.
        /// </summary>
        public static string ToManageYourRequests {
            get {
                return ResourceManager.GetString("ToManageYourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To attend and manage Your requests to Us..
        /// </summary>
        public static string ToManageYourRequestsDescription {
            get {
                return ResourceManager.GetString("ToManageYourRequestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide You.
        /// </summary>
        public static string ToProvideYou {
            get {
                return ResourceManager.GetString("ToProvideYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information..
        /// </summary>
        public static string ToProvideYouDescription {
            get {
                return ResourceManager.GetString("ToProvideYouDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Technologies and Cookies.
        /// </summary>
        public static string TrackingTechnologiesandCookies {
            get {
                return ResourceManager.GetString("TrackingTechnologiesandCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:.
        /// </summary>
        public static string TrackingTechnologiesandCookiesDescription {
            get {
                return ResourceManager.GetString("TrackingTechnologiesandCookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of Your Personal Data.
        /// </summary>
        public static string TransferOfYourPersonalData {
            get {
                return ResourceManager.GetString("TransferOfYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction..
        /// </summary>
        public static string TransferOfYourPersonalDataDescription {
            get {
                return ResourceManager.GetString("TransferOfYourPersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer..
        /// </summary>
        public static string TransferOfYourPersonalDataDescription2 {
            get {
                return ResourceManager.GetString("TransferOfYourPersonalDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information..
        /// </summary>
        public static string TransferOfYourPersonalDataDescription3 {
            get {
                return ResourceManager.GetString("TransferOfYourPersonalDataDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: Persistent Cookies.
        /// </summary>
        public static string TypePersistentCookie {
            get {
                return ResourceManager.GetString("TypePersistentCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: These Cookies identify if users have accepted the use of cookies on the Website..
        /// </summary>
        public static string TypePersistentCookiePurpose {
            get {
                return ResourceManager.GetString("TypePersistentCookiePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website..
        /// </summary>
        public static string TypePersistentCookiePurpose2 {
            get {
                return ResourceManager.GetString("TypePersistentCookiePurpose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: Session Cookies.
        /// </summary>
        public static string TypeSessionCookie {
            get {
                return ResourceManager.GetString("TypeSessionCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Data Collected.
        /// </summary>
        public static string TypesofDataCollected {
            get {
                return ResourceManager.GetString("TypesofDataCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Data.
        /// </summary>
        public static string UsageData {
            get {
                return ResourceManager.GetString("UsageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)..
        /// </summary>
        public static string UsageDataDescription {
            get {
                return ResourceManager.GetString("UsageDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Data is collected automatically when using the Service..
        /// </summary>
        public static string UsageDataDescription2 {
            get {
                return ResourceManager.GetString("UsageDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data..
        /// </summary>
        public static string UsageDataDescription3 {
            get {
                return ResourceManager.GetString("UsageDataDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data..
        /// </summary>
        public static string UsageDataDescription4 {
            get {
                return ResourceManager.GetString("UsageDataDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device..
        /// </summary>
        public static string UsageDataDescription5 {
            get {
                return ResourceManager.GetString("UsageDataDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Your Personal Data.
        /// </summary>
        public static string UseOfYourPersonalData {
            get {
                return ResourceManager.GetString("UseOfYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Beacons..
        /// </summary>
        public static string WebBeacons {
            get {
                return ResourceManager.GetString("WebBeacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)..
        /// </summary>
        public static string WebBeaconsDescription {
            get {
                return ResourceManager.GetString("WebBeaconsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refers to DnD Sheet, accessible from.
        /// </summary>
        public static string WebsiteDescription {
            get {
                return ResourceManager.GetString("WebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.example.com.
        /// </summary>
        public static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share Your personal information in the following situations:.
        /// </summary>
        public static string WeMayShareYourPersonalInformation {
            get {
                return ResourceManager.GetString("WeMayShareYourPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the.
        /// </summary>
        public static string WeUseYourPersonalData {
            get {
                return ResourceManager.GetString("WeUseYourPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Affiliates:.
        /// </summary>
        public static string WithAffiliates {
            get {
                return ResourceManager.GetString("WithAffiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us..
        /// </summary>
        public static string WithAffiliatesDescription {
            get {
                return ResourceManager.GetString("WithAffiliatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With business partners:.
        /// </summary>
        public static string WithBusinessPartners {
            get {
                return ResourceManager.GetString("WithBusinessPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share Your information with Our business partners to offer You certain products, services or promotions..
        /// </summary>
        public static string WithBusinessPartnersDescription {
            get {
                return ResourceManager.GetString("WithBusinessPartnersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With other users:.
        /// </summary>
        public static string WithOtherUsers {
            get {
                return ResourceManager.GetString("WithOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside..
        /// </summary>
        public static string WithOtherUsersDescription {
            get {
                return ResourceManager.GetString("WithOtherUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Service Providers:.
        /// </summary>
        public static string WithServiceProviders {
            get {
                return ResourceManager.GetString("WithServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You..
        /// </summary>
        public static string WithServiceProvidersDescription {
            get {
                return ResourceManager.GetString("WithServiceProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Your consent:.
        /// </summary>
        public static string WithYourConsent {
            get {
                return ResourceManager.GetString("WithYourConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may disclose Your personal information for any other purpose with Your consent..
        /// </summary>
        public static string WithYourConsentDescription {
            get {
                return ResourceManager.GetString("WithYourConsentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable..
        /// </summary>
        public static string YouDescription {
            get {
                return ResourceManager.GetString("YouDescription", resourceCulture);
            }
        }
    }
}
